// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanHWK2sgpg9fIMZTcegubevVBjarc4qY',
    appId: '1:106720567886:web:81055e31566fafdfab591f',
    messagingSenderId: '106720567886',
    projectId: 'projeto-restaurante-gabriel',
    authDomain: 'projeto-restaurante-gabriel.firebaseapp.com',
    storageBucket: 'projeto-restaurante-gabriel.firebasestorage.app',
    measurementId: 'G-E0QWKXNWH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4ok8vBw7pKpOsRxphpcxpN2zRueBGR0A',
    appId: '1:106720567886:android:503cb2466739947cab591f',
    messagingSenderId: '106720567886',
    projectId: 'projeto-restaurante-gabriel',
    storageBucket: 'projeto-restaurante-gabriel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_X8yyUr-jxy52PZb7D4tErBKizk_H6Ms',
    appId: '1:106720567886:ios:bacf0c78724214f6ab591f',
    messagingSenderId: '106720567886',
    projectId: 'projeto-restaurante-gabriel',
    storageBucket: 'projeto-restaurante-gabriel.firebasestorage.app',
    iosBundleId: 'com.example.appRestaurante',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_X8yyUr-jxy52PZb7D4tErBKizk_H6Ms',
    appId: '1:106720567886:ios:bacf0c78724214f6ab591f',
    messagingSenderId: '106720567886',
    projectId: 'projeto-restaurante-gabriel',
    storageBucket: 'projeto-restaurante-gabriel.firebasestorage.app',
    iosBundleId: 'com.example.appRestaurante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCanHWK2sgpg9fIMZTcegubevVBjarc4qY',
    appId: '1:106720567886:web:677bebe6fb3d6cf7ab591f',
    messagingSenderId: '106720567886',
    projectId: 'projeto-restaurante-gabriel',
    authDomain: 'projeto-restaurante-gabriel.firebaseapp.com',
    storageBucket: 'projeto-restaurante-gabriel.firebasestorage.app',
    measurementId: 'G-Y0MSD0RRLM',
  );
}
